#!/usr/bin/env python3
"""Inventory literal UI text and ARB parity; candidates require human review."""
from collections import Counter
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
# Deliberately conservative: direct literal Text/label/hint/tooltip assignments.
PATTERN = re.compile(r'''(?:\bText\(\s*|\b(?:label|title|hintText|tooltip)\s*:\s*)(['"])([^'"\n]+)\1''')
rows = []
counts = Counter()
for path in sorted((ROOT / 'lib/src/presentation').rglob('*.dart')):
    source = path.read_text()
    for match in PATTERN.finditer(source):
        literal = match[2]
        if '$' in literal or not re.search(r'[A-Za-z]{3}', literal):
            continue
        if literal in {'GIF', 'N42', 'N42 Chat', 'N42 AI', 'N42 Bean', 'Matrix', 'Telegram', 'Discord'}:
            continue
        rel = path.relative_to(ROOT)
        line = source[:match.start()].count('\n') + 1
        counts[str(rel.parent)] += 1
        rows.append((str(rel), line, literal.replace('|', '\\|')))

catalog = ROOT / 'lib/l10n'
english = {k: v for k, v in json.loads((catalog / 'app_en.arb').read_text()).items() if not k.startswith('@')}
out = ['# UI translation review — 2026-09-12', '',
       'Generated by `python3 tool/audit_ui_localization.py`. Direct literal candidates are not confirmed translation bugs: brands, examples and syntax may be intentional. Dynamic strings and wrapper methods can be missed. ARB key parity does not prove translation quality.', '',
       '## Catalog parity', '', '| Locale | Missing English keys | Blank values | Same as English |', '|---|---:|---:|---:|']
for path in sorted(catalog.glob('app_*.arb')):
    if path.name == 'app_en.arb':
        continue
    data = json.loads(path.read_text())
    missing = len(set(english) - set(data))
    blank = sum(isinstance(data.get(k), str) and not data[k].strip() for k in english)
    same = sum(data.get(k) == value for k, value in english.items())
    out.append(f'| {path.stem[4:]} | {missing} | {blank} | {same} |')
out += ['', f'## Direct literal candidates ({len(rows)})', '', '| Source | Literal |', '|---|---|']
for path, line, literal in rows:
    out.append(f'| [{path}:{line}](../{path}) | {literal} |')
(ROOT / 'docs/UI_LOCALIZATION_REVIEW_2026-09-12.md').write_text('\n'.join(out) + '\n')
print(f'{len(rows)} literal candidates in {len(counts)} directories')
